config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"
  resources :questions
  resources :users, only: [:show]
  resources :votes, only: [:create]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :votes, as: :voteable, :dependent => :destroy
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :question
  has_many :votes, as: :voteable, :dependent => :destroy

  # scope :chosen, -> (votes) { where(user: user) }
  # scope :chosen, lambda{|user| { :votes.where{ :user_id => user.id, :is_default => true } }

  def get_twin
    self.question.options.each do |option_sibling|
      if option_sibling != option
        return option_sibling
      end
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :options, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  # scope :answered, -> { where(user_id: current_user.id) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
  validates_uniqueness_of :voteable_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password) }
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  def index
    @questions = Question.all
    @question = Question.new
    2.times do @question.options.build end
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    @question.save
    @question.options.create(option_params[:options][0])
    @question.options.create(option_params[:options][1])
    respond_to do |format|
      format.html { redirect_to questions_path }
      format.js
    end
  end

  private
  def question_params
    params.require(:question).permit(:title)
  end
  def option_params
    params.require(:question).permit(:options => [:text, :image_url])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @question = Question.new
    2.times do @question.options.build end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @option = Option.find(params[:option])
    @option.votes.create(user_id: current_user.id)
    @question = @option.question
    respond_to do |format|
      format.html { redirect_to questions_path }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rrrather</title>
  <link href='https://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>
  <link rel="icon" href="http://www.rrrather.com/favicon.ico">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <%= link_to root_path do %>
        <strong class="logo">
          rrrather
        </strong>
      <% end %>
      <div>
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li>
              <%= link_to current_user.username, user_path(current_user) %>
            </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li>
              <a href="#" data-toggle="modal" data-target="#myModal">Ask</a>
            </li>
            <li>
            <%= link_to '<span class="glyphicon glyphicon-log-out"></span> log out'.html_safe, destroy_user_session_path, :method => :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to '<span class="glyphicon glyphicon-log-in"></span> log in'.html_safe, new_user_session_path %>
            </li>
            <li>
              <%= link_to '<span class="glyphicon glyphicon-user"></span> sign up'.html_safe, new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <% if notice || alert %>
    <div class="container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

  <footer>
    <p>
       Copyright 2015 ac & lc & sm |
       <%= link_to 'rrreal rrrather', "http://www.rrrather.com/" %>
       | Cloned in Portland
    </p>
  </footer>

  <% if current_user %>
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">


      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Ask a question</h4>
        </div>
        <div class="modal-body">
          <div class="add_question_form">
            <%= form_for(@question, :remote => true) do |f| %>
              <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field(:title, {:class => 'form-control', :required => 'true'}) %>
              </div>
              <% prefix = "options[]" %>
              <% f.object.options.each do |option| %>
                <%= f.fields_for prefix, option do |option_form| %>
                  <%= option_form.label :text %>
                  <%= option_form.text_field :text %>
                  <%= option_form.label :image_url %>
                  <%= option_form.text_field :image_url %>
                  <br>
                <% end %>
              <% end %>
              <hr>
              <button type="submit" class="btn btn-default">Ask</button>
            <% end %>
          </div>
        </div>



      </div>

    </div>
  </div>
  <% end %>

</body>
</html>

app/views/questions/_question.html.erb
<div class="cols clearfix" id="question<%= question.id %>">
  <div class="holder clearfix rrrather">

    <div class="col-xs-7">
      <h2><%= question.title %>... <span>(By <%= link_to question.user.username, user_path(question.user) %> <%= time_ago_in_words question.created_at %> ago)</span></h2>
      <% if Vote.where(user_id: current_user.id, voteable_id: question.options.first.id).any? || Vote.where(user_id: current_user.id, voteable_id: question.options.last.id).any?%>
        <div class="text-center col-xs-5 <%= Vote.where(user_id: current_user.id, voteable_id: question.options.first.id).any? ? 'selected' : 'unselected' %>">
          <div class="photo-insert" style="background-image: url(<%= question.options.first.image_url %>);">

          </div>
          <h4><%= question.options.first.text %></h4>
        </div>
        <div class="col-xs-2 text-center">
          <br><br>
          <h2>OR</h2>
          <h5 class="votes"><%= question.options.first.votes.count + question.options.last.votes.count %> votes</h5>
        </div>
        <div class="col-xs-5 text-center photo-tile" id="option<%= question.options.last.id %>">
          <div class="photo-insert" style="background-image: url(<%= question.options.last.image_url %>);">

          </div>
          <h4><%= question.options.last.text %></h4>
        </div>
      <% else %>
        <%= link_to votes_path(option: question.options.first), :remote => true, method: :post do %>
        <div class="text-center col-xs-5 <%= Vote.where(user_id: current_user.id, voteable_id: question.options.last.id).any? ? 'selected' : 'unselected' %>">
          <div class="photo-insert" style="background-image: url(<%= question.options.first.image_url %>);">

          </div>
          <h4><%= question.options.first.text %></h4>
        </div>
        <% end %>
        <div class="col-xs-2 text-center">
          <br><br>
          <h2>OR</h2>
          <h5 class="votes"><%= question.options.first.votes.count + question.options.last.votes.count %> votes</h5>
        </div>
        <%= link_to votes_path(option: question.options.last), :remote => true, method: :post do %>
          <div class="col-xs-5 text-center photo-tile" id="option<%= question.options.last.id %>">
            <div class="photo-insert" style="background-image: url(<%= question.options.last.image_url %>);">

            </div>
            <h4><%= question.options.last.text %></h4>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-xs-5 comment-box">
      <h3>Leave a comment</h3>
    </div>
  </div>
</div>
<br>

app/views/questions/create.js.erb
$('.questions').append("<%= j render 'question', :question => @question %>");
$('#myModal').modal('hide');

app/views/questions/index.html.erb
<h1>What would you rather?</h1>

<div class="questions">
<% @questions.each do |question| %>
<%= render 'question', :question => question %>
<% end %>
</div>

app/views/users/show.html.erb
<h1>(profile page for <%= @user.username %>)</h1>

app/views/votes/create.js.erb
$('#question<%= @question.id %>').find('.photo-tile').removeClass('photo-tile').addClass('unselected');
$('#question<%= @question.id %>').find('.photo-tile > a').css('color', 'grey');
$('#question<%= @question.id %>').find('a').removeAttr('href');
$('#question<%= @question.id %>').find('.votes').text('<%= @question.options.first.votes.count + @question.options.last.votes.count %> votes');
$('#option<%= @option.id %>').removeClass('unselected').addClass('selected');